# Generated by Django 4.2.8 on 2023-12-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('wikepedia_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('mailid', models.EmailField(max_length=300)),
                ('address', models.TextField(max_length=400)),
                ('district', models.TextField(max_length=400)),
                ('account_type', models.CharField(max_length=300)),
                ('materials_provide', models.TextField(max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankingapp.branch')),
            ],
        ),
    ]
