# Generated by Django 4.2.8 on 2023-12-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0002_branch_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='slug',
            field=models.SlugField(default=2, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='slug',
            field=models.SlugField(default=4555, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
